spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000

  data:
    redis:
      host: redis
      port: 6379

  sql:
    init:
      mode: never

  # elasticsearch:
  #   uris: "${server.address}:9200"
  #   username: elastic

  main:
    allow-bean-definition-overriding: true

logging.level:
  org.hibernate.SQL: debug  # SQL 쿼리 출력
  com.zaxxer.hikari.HikariConfig: debug  # HikariCP 설정 정보 출력
  com.zaxxer.hikari: debug  # HikariCP 연결 상태 출력

server:
  port: 80

oauth:
  kakao:
    redirect-uri: https://www.aieng.co.kr/oauth/kakao/callback
  google:
    redirect-uri: https://www.aieng.co.kr/oauth/google/callback
  naver:
    redirect-uri: https://www.aieng.co.kr/oauth/naver/callback

app:
  domain: http://www.aieng.co.kr

external:
  fastapi:
    base-url: "http://175.121.93.70:51528"

aws:
  s3:
    bucket: aieng
  region: ap-northeast-2
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
