spring:
  profiles:
    include: secret
    active: dev
  data:
    web:
      pageable:
        one-indexed-parameters: true # 0이 아닌 1부터

  jpa:
    open-in-view: false

aws:
  s3:
    bucket: aieng
  region: ap-northeast-2
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
