app:
  domain: http://localhost:5173

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  datasource:
    url: jdbc:mariadb://localhost:3306/aieng
    username: aieng
    password: b104B104
    driver-class-name: org.mariadb.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password:

  sql:
    init:
      mode: always

  main:
    allow-bean-definition-overriding: true


logging:
  level:
    root: debug  # 전체 로그 레벨을 debug로 설정 (추천)
    com.ssafy.aieng: debug  # 또는 특정 패키지에 대해서만 debug로 설정

    org.hibernate.SQL: warn
    com.zaxxer.hikari.HikariConfig: OFF
    com.zaxxer.hikari: OFF

oauth:
  kakao:
    redirect-uri: http://localhost:8080/oauth/kakao/callback
  google:
    redirect-uri: http://localhost:5173/oauth/google/callback
  naver:
    redirect-uri: http://localhost:5173/oauth/naver/callback
