app:
  domain: http://localhost:5173

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  datasource:
    url: jdbc:mariadb://localhost:3306/aieng
    username: aieng
    password: b104B104
    driver-class-name: org.mariadb.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password: ""

management:
  health:
    elasticsearch:
      enabled: false