spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    defer-datasource-initialization: false

  datasource:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000

  data:
    redis:
      host: ${server.address}

  sql:
    init:
      mode: never

  elasticsearch:
    uris: "${server.address}:9200"
    username: elastic

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: debug  # 전체 로그 레벨을 debug로 설정 (추천)
    com.ssafy.aieng: debug  # 또는 특정 패키지에 대해서만 debug로 설정

    org.hibernate.SQL: warn
    com.zaxxer.hikari.HikariConfig: OFF
    com.zaxxer.hikari: OFF

server:
  port: 80

oauth:
  kakao:
    redirect-uri: https://www.aieng.co.kr/oauth/kakao/callback
  google:
    redirect-uri: https://www.aieng.co.kr/oauth/google/callback
  naver:
    redirect-uri: https://www.aieng.co.kr/oauth/naver/callback

